/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentancion;

import Negocio1.Casino;
import java.time.LocalDate;
import javax.swing.JLabel;
import Presentacion.Ventana;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author saraj
 */
public class Blackjack extends javax.swing.JFrame {

    private Principal myPrincipal;
    private Casino myCasino;
    private JLabel etiquetas[];
    private boolean crupier = false;

    /**
     * Creates new form Blackjack
     */
    public Blackjack(Principal myPrincipal, Casino myCasino) {
        initComponents();
        this.myPrincipal = myPrincipal;
        this.myCasino = myCasino;
        LocalDate dt = LocalDate.now();
        this.lblFecha.setText(dt.toString());
        this.myPrincipal.getMyCasino();

        ArrayList<String> jugadores = this.myCasino.listadoJug();

        for (String jug : jugadores) {
            this.cmbJug1.addItem(jug);
            this.cmbJug2.addItem(jug);
        }

    }

    public Blackjack(Principal myPrincipal, Casino myCasino, boolean crupier) {
        initComponents();
        this.myPrincipal = myPrincipal;
        this.myCasino = myCasino;
        LocalDate dt = LocalDate.now();
        this.lblFecha.setText(dt.toString());
        this.myPrincipal.getMyCasino();
        this.crupier = true;

        ArrayList<String> jugadores = this.myCasino.listadoJug();
        ArrayList<String> crupiers = this.myCasino.listadoCru();

        for (String jug : jugadores) {
            this.cmbJug1.addItem(jug);
        }
        for (String cru : crupiers) {
            this.cmbJug2.addItem(cru);
        }

    }

    public Principal getMyPrincipal() {
        return myPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        lblNumeroPartido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnOtra1 = new javax.swing.JButton();
        btnStop1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJugadores = new javax.swing.JTextArea();
        btnNuevo = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnOtra2 = new javax.swing.JButton();
        btnStop2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelJug2 = new javax.swing.JPanel();
        lblJapuesta2 = new javax.swing.JLabel();
        lblJnombre2 = new javax.swing.JLabel();
        txtApuesta2 = new javax.swing.JTextField();
        lblJ2 = new javax.swing.JLabel();
        cmbJug2 = new javax.swing.JComboBox<>();
        panelJug1 = new javax.swing.JPanel();
        lblJapuesta1 = new javax.swing.JLabel();
        lblJnombre1 = new javax.swing.JLabel();
        txtApuesta1 = new javax.swing.JTextField();
        lblJ1 = new javax.swing.JLabel();
        cmbJug1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblC1J1 = new javax.swing.JLabel();
        lblC2J1 = new javax.swing.JLabel();
        lblC3J1 = new javax.swing.JLabel();
        lblC5J1 = new javax.swing.JLabel();
        lblC4J1 = new javax.swing.JLabel();
        lblC5J2 = new javax.swing.JLabel();
        lblC4J2 = new javax.swing.JLabel();
        lblC1J2 = new javax.swing.JLabel();
        lblC2J2 = new javax.swing.JLabel();
        lblC3J2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPuntaje1Mod = new javax.swing.JLabel();
        lblPuntaje2Mod = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();
        lblPuntJug1 = new javax.swing.JLabel();
        lblPuntJug2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelPrincipal.setBackground(new java.awt.Color(51, 153, 0));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        lblNumeroPartido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroPartido.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroPartido.setText("Partido No.");

        jLabel2.setFont(new java.awt.Font("HYMyeongJo-Extra", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BLACKJACK");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha:");

        btnOtra1.setBackground(new java.awt.Color(204, 0, 0));
        btnOtra1.setForeground(new java.awt.Color(255, 255, 255));
        btnOtra1.setText("Otra carta");
        btnOtra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtra1ActionPerformed(evt);
            }
        });

        btnStop1.setBackground(new java.awt.Color(204, 0, 0));
        btnStop1.setForeground(new java.awt.Color(255, 255, 255));
        btnStop1.setText("Stop");
        btnStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop1ActionPerformed(evt);
            }
        });

        txtJugadores.setColumns(20);
        txtJugadores.setRows(5);
        txtJugadores.setEnabled(false);
        jScrollPane1.setViewportView(txtJugadores);

        btnNuevo.setBackground(new java.awt.Color(204, 204, 0));
        btnNuevo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setEnabled(false);
        btnNuevo.setOpaque(true);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(255, 255, 0));
        btnStart.setForeground(new java.awt.Color(204, 0, 0));
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnSaldo.setBackground(new java.awt.Color(204, 204, 0));
        btnSaldo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        btnSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnSaldo.setText("Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnOtra2.setBackground(new java.awt.Color(204, 0, 0));
        btnOtra2.setForeground(new java.awt.Color(255, 255, 255));
        btnOtra2.setText("Otra carta");
        btnOtra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtra2ActionPerformed(evt);
            }
        });

        btnStop2.setBackground(new java.awt.Color(204, 0, 0));
        btnStop2.setForeground(new java.awt.Color(255, 255, 255));
        btnStop2.setText("Stop");
        btnStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop2ActionPerformed(evt);
            }
        });

        jLabel14.setText("jLabel12");

        panelJug2.setBackground(new java.awt.Color(153, 204, 0));
        panelJug2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        lblJapuesta2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJapuesta2.setForeground(new java.awt.Color(255, 255, 255));
        lblJapuesta2.setText("APUESTA*");

        lblJnombre2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJnombre2.setForeground(new java.awt.Color(255, 255, 255));
        lblJnombre2.setText("USUARIO");

        txtApuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApuesta2ActionPerformed(evt);
            }
        });

        lblJ2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lblJ2.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2.setText("JUGADOR 2");

        cmbJug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJug2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJug2Layout = new javax.swing.GroupLayout(panelJug2);
        panelJug2.setLayout(panelJug2Layout);
        panelJug2Layout.setHorizontalGroup(
            panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJug2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelJug2Layout.createSequentialGroup()
                        .addComponent(lblJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelJug2Layout.createSequentialGroup()
                        .addGroup(panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJug2Layout.createSequentialGroup()
                                .addComponent(lblJapuesta2)
                                .addGap(15, 15, 15))
                            .addGroup(panelJug2Layout.createSequentialGroup()
                                .addComponent(lblJnombre2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbJug2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        panelJug2Layout.setVerticalGroup(
            panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJug2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJug2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelJug2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJapuesta2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelJug1.setBackground(new java.awt.Color(153, 204, 0));
        panelJug1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        lblJapuesta1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJapuesta1.setForeground(new java.awt.Color(255, 255, 255));
        lblJapuesta1.setText("APUESTA*");

        lblJnombre1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJnombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblJnombre1.setText("USUARIO");

        txtApuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApuesta1ActionPerformed(evt);
            }
        });

        lblJ1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lblJ1.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1.setText("JUGADOR 1");

        cmbJug1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJug1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelJug1Layout = new javax.swing.GroupLayout(panelJug1);
        panelJug1.setLayout(panelJug1Layout);
        panelJug1Layout.setHorizontalGroup(
            panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJug1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelJug1Layout.createSequentialGroup()
                        .addGroup(panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelJug1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblJapuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblJnombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApuesta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(cmbJug1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(panelJug1Layout.createSequentialGroup()
                        .addComponent(lblJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelJug1Layout.setVerticalGroup(
            panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJug1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJug1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelJug1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJapuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));

        lblC1J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC2J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC3J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC5J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC4J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC5J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC4J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC1J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC2J2.setAlignmentX(0.5F);
        lblC2J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC3J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPuntaje1Mod.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblPuntaje1Mod.setText("0");

        lblPuntaje2Mod.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        lblPuntaje2Mod.setText("0");

        lblPuntaje.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        lblPuntaje.setText("PUNTAJE");

        lblPuntJug1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        lblPuntJug1.setText("JUG 1");

        lblPuntJug2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        lblPuntJug2.setText("JUG 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblPuntJug1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(lblPuntJug2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblPuntaje1Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPuntaje2Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPuntaje)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPuntaje)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntJug1)
                    .addComponent(lblPuntJug2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPuntaje1Mod)
                    .addComponent(lblPuntaje2Mod))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblC4J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lblC5J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblC1J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblC2J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblC3J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblC1J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblC2J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblC3J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblC4J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblC5J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblC1J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC2J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC3J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC4J2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC5J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC3J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblC1J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblC2J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC4J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC5J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jButton1.setText("Volver Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblNumeroPartido)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(panelJug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelJug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnOtra1)
                        .addGap(53, 53, 53)
                        .addComponent(btnStop1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(btnOtra2)
                        .addGap(34, 34, 34)
                        .addComponent(btnStop2)
                        .addGap(123, 123, 123))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaldo)
                        .addGap(57, 57, 57)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(jLabel2)
                    .addComponent(lblNumeroPartido))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelJug1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelJug2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOtra2)
                            .addComponent(btnStop2)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOtra1)
                            .addComponent(btnStop1))))
                .addGap(28, 28, 28)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo)
                        .addComponent(btnSaldo)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApuesta2ActionPerformed

    private void btnOtra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtra2ActionPerformed
        // TODO add your handling code here:
        if (!this.crupier) {
            String carta = this.myCasino.llamarOtraCarta(1);

            if (carta.equalsIgnoreCase("Perdio")) {
                Ventana.imp("Ha perdido, su puntaje es mayor de 21, finalizando partida", "Sistema");
                this.btnOtra2.setEnabled(false);
                this.btnStop2.setEnabled(false);
                return;
            }
            if (carta.equalsIgnoreCase("Solo5")) {
                Ventana.imp("Solo puede tener 5 cartas", "Sistema");
                this.btnOtra2.setEnabled(false);
                this.btnStop2.setEnabled(false);
                return;
            }

            this.lblPuntaje2Mod.setText(this.myCasino.mostrarPuntaje(1));
            JLabel cartasEtiquetas[] = {this.lblC3J2, this.lblC4J2, this.lblC5J2};
            for (JLabel l : cartasEtiquetas) {
                if (l.getText().isEmpty()) {
                    l.setText(carta);
                    break;
                }
            }
            this.plantarseAuto(1);
        }

    }//GEN-LAST:event_btnOtra2ActionPerformed

    public void otraCartaCrupier() {
        int puntajeCrup = Integer.parseInt(this.lblPuntaje2Mod.getText());
        while (this.crupier && puntajeCrup < 17) {
            String carta = this.myCasino.llamarOtraCarta(1);

            if (carta.equalsIgnoreCase("Perdio")) {
                Ventana.imp("Ha perdido, su puntaje es mayor de 21, finalizando partida", "Sistema");
                this.lblPuntaje2Mod.setText(this.myCasino.mostrarPuntaje(1));
                return;
            }
            if (carta.equalsIgnoreCase("Solo5")) {
                Ventana.imp("Solo puede tener 5 cartas", "Sistema");
                return;
            }

            this.lblPuntaje2Mod.setText(this.myCasino.mostrarPuntaje(1));
            JLabel cartasEtiquetas[] = {this.lblC3J2, this.lblC4J2, this.lblC5J2};
            for (JLabel l : cartasEtiquetas) {
                if (l.getText().isEmpty()) {
                    l.setText(carta);
                    break;
                }
            }
            puntajeCrup = Integer.parseInt(this.lblPuntaje2Mod.getText());
        }

        this.btnNuevo.setEnabled(true);
    }


    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this.limpiarVista();
        this.btnOtra1.setEnabled(false);
        this.btnOtra2.setEnabled(false);
        this.btnStop1.setEnabled(false);
        this.btnStop2.setEnabled(false);
        this.lblPuntaje1Mod.setText("");
        this.lblPuntaje2Mod.setText("");
        this.btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    public void limpiarVista() {
        this.txtApuesta1.setText("");
        this.txtApuesta2.setText("");
        this.lblPuntaje1Mod.setText("0");
        this.lblPuntaje2Mod.setText("0");
        this.lblC1J1.setText("");
        this.lblC2J1.setText("");
        this.lblC3J1.setText("");
        this.lblC4J1.setText("");
        this.lblC5J1.setText("");
        this.lblC1J2.setText("");
        this.lblC2J2.setText("");
        this.lblC3J2.setText("");
        this.lblC4J2.setText("");
        this.lblC5J2.setText("");
        this.txtJugadores.setText("");
    }

    private void txtApuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApuesta1ActionPerformed

    private void btnStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop2ActionPerformed
        // TODO add your handling code here
        int puntosJug2 = Integer.parseInt(this.lblPuntaje2Mod.getText());
        if (puntosJug2 < 17) {
            Ventana.imp("¡No puedes plantarte!, tus puntos no llegan a 17", "Sistema");
            return;
        }
        this.btnOtra2.setEnabled(false);
        this.btnStop2.setEnabled(false);
        if (!this.crupier) {
            this.btnNuevo.setEnabled(true);
            String cad = this.myCasino.ganador();
            this.txtJugadores.setText(cad);
        }

    }//GEN-LAST:event_btnStop2ActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
        String informeSaldo = this.myCasino.saldo();
        this.txtJugadores.setText(informeSaldo);
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop1ActionPerformed
        // TODO add your handling code here:
        int puntosJug1 = Integer.parseInt(this.lblPuntaje1Mod.getText());
        if (puntosJug1 < 17) {
            Ventana.imp("¡No puedes plantarte!, tus puntos no llegan a 17", "Sistema");
            return;
        }
        this.btnOtra1.setEnabled(false);
        this.btnStop1.setEnabled(false);
        if (this.crupier) {
            this.otraCartaCrupier();
            String resultado = this.myCasino.ganadorCrupier();
            this.txtJugadores.setText(resultado);

        }
        if (!this.crupier) {
            this.btnOtra2.setEnabled(true);
            this.btnStop2.setEnabled(true);
        }

    }//GEN-LAST:event_btnStop1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        this.btnOtra1.setEnabled(true);
        this.btnStop1.setEnabled(true);
        this.btnOtra2.setEnabled(false);
        this.btnStop2.setEnabled(false);

        if (this.cmbJug1.getSelectedItem().toString().equals(this.cmbJug2.getSelectedItem().toString())) {
            Ventana.imp("No puede jugar contra el mismo", "Sistema");
            return;
        }
        /*String cad=this.myCasino.haberBlackJackCrupier();
        if(cad.equalsIgnoreCase("No se puede iniciar la partida porque el jugador lleva 10 partidas")){
            
        }*/

        if (this.crupier) {
            this.startCrupier();
            String cad = this.myCasino.haberBlackJackCrupier();
            if (!cad.equalsIgnoreCase("No hay BlackJack,¡Sigue jugador 1! :D")) {
                this.txtJugadores.setText(cad);
                this.btnOtra1.setEnabled(false);
                this.btnStop1.setEnabled(false);
                this.btnOtra2.setEnabled(false);
                this.btnStop2.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }
        }
        if (!this.crupier) {
            this.startJugador();
            String cad = this.myCasino.haberBlackJack();
            if (!cad.equalsIgnoreCase("No hay BlackJack,¡Sigue jugador 1! :D")) {
                this.txtJugadores.setText(cad);
                this.btnOtra1.setEnabled(false);
                this.btnStop1.setEnabled(false);
                this.btnOtra2.setEnabled(false);
                this.btnStop2.setEnabled(false);
                this.btnNuevo.setEnabled(true);
            }
        }

        this.lblPuntaje1Mod.setText(this.myCasino.mostrarPuntaje(0));
        this.lblPuntaje2Mod.setText(this.myCasino.mostrarPuntaje(1));

    }//GEN-LAST:event_btnStartActionPerformed

    private void startJugador() {
        if (this.txtApuesta1.getText().isEmpty() || this.txtApuesta2.getText().isEmpty()) {
            Ventana.imp("¡Digite todos los campos!", "Sistema");
            return;
        }
        this.btnOtra2.setEnabled(false);
        this.btnStop2.setEnabled(false);
        this.cmbJug1.enableInputMethods(false);
        this.cmbJug2.enableInputMethods(false);

        String dato1 = this.cmbJug1.getSelectedItem().toString();
        String ced1[] = dato1.split("-");
        String cedula1 = ced1[1];
        String dato2 = this.cmbJug2.getSelectedItem().toString();
        String ced2[] = dato2.split("-");
        String cedula2 = ced2[1];

        int apuesta1 = Integer.parseInt(this.txtApuesta1.getText());
        int apuesta2 = Integer.parseInt(this.txtApuesta2.getText());

        if (this.myCasino.dineroNoSuficiente()) {
            Ventana.imp("No hay dinero suficiente", "Sistema");
            while (this.myCasino.getMyCaja() < 150000) {
                int cajaAgregar = Ventana.leerInt("Digite la cantidad de dinero que se va añadir a la caja");
                this.myCasino.setMyCaja(this.myCasino.getMyCaja() + cajaAgregar);
            }
        }

        String fecha = this.lblFecha.getText();

        String[] cartas = this.myCasino.startBlackjackDos(apuesta1, apuesta2, cedula1, cedula2, fecha);
        if (cartas.length == 1) {
            Ventana.imp(cartas[0], "Sistema");
            return;
        }
        JLabel cartasEtiqueda[] = {this.lblNumeroPartido, this.lblC1J1, this.lblC2J1, this.lblC1J2, this.lblC2J2};
        this.etiquetas = cartasEtiqueda;
        for (int i = 0; i < cartasEtiqueda.length; i++) {
            cartasEtiqueda[i].setText(cartas[i]);
        }
    }

    private void startCrupier() {
        if (this.txtApuesta1.getText().isEmpty()) {
            Ventana.imp("¡Digite todos los campos!", "Sistema");
            return;
        }
        this.btnOtra2.setEnabled(false);
        this.btnStop2.setEnabled(false);

        String dato1 = this.cmbJug1.getSelectedItem().toString();
        String ced1[] = dato1.split("-");
        String cedula1 = ced1[1];
        String dato2 = this.cmbJug2.getSelectedItem().toString();
        String ced2[] = dato2.split("-");
        String cedula2 = ced2[1];

        int apuesta1 = Integer.parseInt(this.txtApuesta1.getText());
        this.txtApuesta2.setText(this.txtApuesta1.getText());
        int apuesta2 = apuesta1;

        if (this.myCasino.dineroNoSuficiente()) {
            Ventana.imp("No hay dinero suficiente", "Sistema");
            while (this.myCasino.getMyCaja() < 150000) {
                int cajaAgregar = Ventana.leerInt("Digite la cantidad de dinero que se va añadir a la caja");
                this.myCasino.setMyCaja(this.myCasino.getMyCaja() + cajaAgregar);
            }
        }

        String fecha = this.lblFecha.getText();
        String[] cartas = this.myCasino.StartBlackjackUno(apuesta1, apuesta2, cedula1, cedula2, fecha);
        if (cartas.length == 1) {
            Ventana.imp(cartas[0], "Sistema");
            return;
        }
        JLabel cartasEtiqueda[] = {this.lblNumeroPartido, this.lblC1J1, this.lblC2J1, this.lblC1J2, this.lblC2J2};
        this.etiquetas = cartasEtiqueda;
        for (int i = 0; i < cartasEtiqueda.length; i++) {
            cartasEtiqueda[i].setText(cartas[i]);
        }

    }

    public void modificarLblJug2() {
        this.lblJ2.setText("CRUPIER");
        this.lblJ1.setText("JUGADOR");
        this.lblPuntJug2.setText("CRUPIER");
        this.txtApuesta2.setEnabled(false);
        this.txtApuesta2.setText("(Igual a la otra apuesta)");
        this.btnOtra2.setVisible(false);
        this.btnStop2.setVisible(false);

    }

    private void btnOtra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtra1ActionPerformed
        // TODO add your handling code here:
        String carta = this.myCasino.llamarOtraCarta(0);

        if (carta.equalsIgnoreCase("Perdio")) {
            Ventana.imp("Ha perdido, su puntaje es mayor de 21, sigue jugador 2", "Sistema");
            this.btnOtra1.setEnabled(false);
            this.btnStop1.setEnabled(false);
            if (crupier) {
                String resultado = this.myCasino.ganadorCrupier();
                this.txtJugadores.setText(resultado);
                return;
            }
            this.btnOtra2.setEnabled(true);
            this.btnStop2.setEnabled(true);
            return;
        }
        if (carta.equalsIgnoreCase("Solo5")) {
            Ventana.imp("Solo puede tener 5 cartas", "Sistema");
            this.btnOtra1.setEnabled(false);
            this.btnStop1.setEnabled(false);
            if (crupier) {
                String resultado = this.myCasino.ganadorCrupier();
                this.txtJugadores.setText(resultado);
                return;
            }
            this.btnOtra2.setEnabled(true);
            this.btnStop2.setEnabled(true);
            return;
        }

        this.lblPuntaje1Mod.setText(this.myCasino.mostrarPuntaje(0));
        JLabel cartasEtiquetas[] = {this.lblC3J1, this.lblC4J1, this.lblC5J1};
        for (JLabel l : cartasEtiquetas) {
            if (l.getText().isEmpty()) {
                l.setText(carta);
                break;
            }
        }
        this.plantarseAuto(0);

        /*if (this.crupier) {
            this.txtJugadores.setText("");
        }*/
    }//GEN-LAST:event_btnOtra1ActionPerformed

    private void plantarseAuto(int index) {
        int puntaje;
        if (index == 0) {
            puntaje = Integer.parseInt(this.lblPuntaje1Mod.getText().toString());
            if (puntaje >= 21) {
                this.btnStop1.doClick();
            }
            return;
        }
        puntaje = Integer.parseInt(this.lblPuntaje2Mod.getText().toString());
        if (puntaje >= 21) {
            this.btnStop2.doClick();
        }

    }
    private void cmbJug1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJug1ActionPerformed
        // TODO add your handling code here:
        //this.jug1Seleccionado();

    }//GEN-LAST:event_cmbJug1ActionPerformed

    private void cmbJug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJug2ActionPerformed
        // TODO add your handling code here:
        //this.jug2Seleccionado();
    }//GEN-LAST:event_cmbJug2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.limpiarVista();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    private void jug1Seleccionado() {
        try {
            String jug1 = this.cmbJug1.getSelectedItem().toString();
            String jug2 = this.cmbJug2.getSelectedItem().toString();
            ArrayList<String> jugadores = this.myCasino.listadoJug();
            if (jug1.isEmpty()) {
                jug1 = "";
            }
            if (jug2.isEmpty()) {
                jug2 = "";
            }

            for (int i = 0; i < jugadores.size(); i++) {
                if (jugadores.get(i).equalsIgnoreCase(jug1)) {
                    this.cmbJug2.remove(i);
                    this.cmbJug2.setEnabled(true);
                    this.cmbJug1.setEditable(false);
                }
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void jug2Seleccionado() {
        try {
            String jug1 = this.cmbJug1.getSelectedItem().toString();
            String jug2 = this.cmbJug2.getSelectedItem().toString();
            ArrayList<String> jugadores = this.myCasino.listadoJug();

            if (jug1.isEmpty()) {
                jug1 = "";
            }
            if (jug2.isEmpty()) {
                jug2 = "";
            }

            for (int i = 0; i < jugadores.size(); i++) {
                if (jugadores.get(i).equalsIgnoreCase(jug2)) {
                    this.cmbJug1.remove(i);
                    this.cmbJug1.setEnabled(true);
                    this.cmbJug2.setEditable(false);
                }
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }

    public JComboBox<String> getCmbJug2() {
        return cmbJug2;
    }

    public void setCmbJug2(JComboBox<String> cmbJug2) {
        this.cmbJug2 = cmbJug2;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOtra1;
    private javax.swing.JButton btnOtra2;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop1;
    private javax.swing.JButton btnStop2;
    private javax.swing.JComboBox<String> cmbJug1;
    private javax.swing.JComboBox<String> cmbJug2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblC1J1;
    private javax.swing.JLabel lblC1J2;
    private javax.swing.JLabel lblC2J1;
    private javax.swing.JLabel lblC2J2;
    private javax.swing.JLabel lblC3J1;
    private javax.swing.JLabel lblC3J2;
    private javax.swing.JLabel lblC4J1;
    private javax.swing.JLabel lblC4J2;
    private javax.swing.JLabel lblC5J1;
    private javax.swing.JLabel lblC5J2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblJapuesta1;
    private javax.swing.JLabel lblJapuesta2;
    private javax.swing.JLabel lblJnombre1;
    private javax.swing.JLabel lblJnombre2;
    private javax.swing.JLabel lblNumeroPartido;
    private javax.swing.JLabel lblPuntJug1;
    private javax.swing.JLabel lblPuntJug2;
    private javax.swing.JLabel lblPuntaje;
    private javax.swing.JLabel lblPuntaje1Mod;
    private javax.swing.JLabel lblPuntaje2Mod;
    private javax.swing.JPanel panelJug1;
    private javax.swing.JPanel panelJug2;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtApuesta1;
    private javax.swing.JTextField txtApuesta2;
    private javax.swing.JTextArea txtJugadores;
    // End of variables declaration//GEN-END:variables
}
