/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentancion;

import Negocio1.Casino;
import java.time.LocalDate;
import javax.swing.JLabel;

/**
 *
 * @author saraj
 */
public class Blackjack extends javax.swing.JFrame {

    private Principal myPrincipal;
    private Casino myCasino;
    private JLabel etiquetas[];

    /**
     * Creates new form Blackjack
     */
    public Blackjack(Principal myPrincipal, Casino myCasino) {
        initComponents();
        this.myPrincipal = myPrincipal;
        this.myCasino = myCasino;
        LocalDate dt = LocalDate.now();
        this.lblFecha.setText(dt.toString());
        this.myPrincipal.getMyCasino();
    }

    public Principal getMyPrincipal() {
        return myPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnOtra = new javax.swing.JPanel();
        lblNumeroPartido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnOtra1 = new javax.swing.JButton();
        btnStop1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJug2 = new javax.swing.JTextArea();
        btnNuevo = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        btnEvaluar = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnOtra2 = new javax.swing.JButton();
        btnStop2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJug1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblJapuesta2 = new javax.swing.JLabel();
        lblJnombre2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        txtApuesta2 = new javax.swing.JTextField();
        lblJ2 = new javax.swing.JLabel();
        lblJnombre3 = new javax.swing.JLabel();
        txtCedula2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblJapuesta1 = new javax.swing.JLabel();
        lblJnombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtApuesta1 = new javax.swing.JTextField();
        lblJ1 = new javax.swing.JLabel();
        lblJapuesta3 = new javax.swing.JLabel();
        txtCedula1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblC1J1 = new javax.swing.JLabel();
        lblC2J1 = new javax.swing.JLabel();
        lblC3J1 = new javax.swing.JLabel();
        lblC5J1 = new javax.swing.JLabel();
        lblC4J1 = new javax.swing.JLabel();
        lblC5J2 = new javax.swing.JLabel();
        lblC4J2 = new javax.swing.JLabel();
        lblC1J2 = new javax.swing.JLabel();
        lblC2J2 = new javax.swing.JLabel();
        lblC3J2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnOtra.setBackground(new java.awt.Color(51, 153, 0));
        btnOtra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 4));

        lblNumeroPartido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroPartido.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroPartido.setText("Partido No.");

        jLabel2.setFont(new java.awt.Font("HYMyeongJo-Extra", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BLACKJACK");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha:");

        btnOtra1.setBackground(new java.awt.Color(204, 0, 0));
        btnOtra1.setForeground(new java.awt.Color(255, 255, 255));
        btnOtra1.setText("Otra carta");
        btnOtra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtra1ActionPerformed(evt);
            }
        });

        btnStop1.setBackground(new java.awt.Color(204, 0, 0));
        btnStop1.setForeground(new java.awt.Color(255, 255, 255));
        btnStop1.setText("Stop");
        btnStop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop1ActionPerformed(evt);
            }
        });

        txtJug2.setColumns(20);
        txtJug2.setRows(5);
        jScrollPane1.setViewportView(txtJug2);

        btnNuevo.setBackground(new java.awt.Color(204, 204, 0));
        btnNuevo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnStart.setBackground(new java.awt.Color(255, 255, 0));
        btnStart.setForeground(new java.awt.Color(204, 0, 0));
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnEvaluar.setBackground(new java.awt.Color(204, 204, 0));
        btnEvaluar.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        btnEvaluar.setForeground(new java.awt.Color(255, 255, 255));
        btnEvaluar.setText("Evaluar");

        btnSaldo.setBackground(new java.awt.Color(204, 204, 0));
        btnSaldo.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        btnSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnSaldo.setText("Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnOtra2.setBackground(new java.awt.Color(204, 0, 0));
        btnOtra2.setForeground(new java.awt.Color(255, 255, 255));
        btnOtra2.setText("Otra carta");
        btnOtra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtra2ActionPerformed(evt);
            }
        });

        btnStop2.setBackground(new java.awt.Color(204, 0, 0));
        btnStop2.setForeground(new java.awt.Color(255, 255, 255));
        btnStop2.setText("Stop");
        btnStop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStop2ActionPerformed(evt);
            }
        });

        txtJug1.setColumns(20);
        txtJug1.setRows(5);
        jScrollPane2.setViewportView(txtJug1);

        jLabel14.setText("jLabel12");

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        lblJapuesta2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJapuesta2.setForeground(new java.awt.Color(255, 255, 255));
        lblJapuesta2.setText("APUESTA*");

        lblJnombre2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJnombre2.setForeground(new java.awt.Color(255, 255, 255));
        lblJnombre2.setText("NOMBRE");

        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });

        txtApuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApuesta2ActionPerformed(evt);
            }
        });

        lblJ2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lblJ2.setForeground(new java.awt.Color(255, 255, 255));
        lblJ2.setText("JUGADOR 2");

        lblJnombre3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJnombre3.setForeground(new java.awt.Color(255, 255, 255));
        lblJnombre3.setText("CEDULA*");

        txtCedula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJapuesta2)
                        .addGap(15, 15, 15)
                        .addComponent(txtApuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula2)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblJ2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJapuesta2))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        lblJapuesta1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJapuesta1.setForeground(new java.awt.Color(255, 255, 255));
        lblJapuesta1.setText("APUESTA*");

        lblJnombre1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJnombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblJnombre1.setText("NOMBRE");

        txtNombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombre1MousePressed(evt);
            }
        });
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        txtApuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApuesta1ActionPerformed(evt);
            }
        });

        lblJ1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        lblJ1.setForeground(new java.awt.Color(255, 255, 255));
        lblJ1.setText("JUGADOR 1");

        lblJapuesta3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lblJapuesta3.setForeground(new java.awt.Color(255, 255, 255));
        lblJapuesta3.setText("CEDULA*");

        txtCedula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedula1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblJnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblJapuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblJapuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCedula1)
                            .addComponent(txtApuesta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJapuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJapuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));

        lblC1J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC2J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC3J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC5J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC4J1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC5J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC4J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC1J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC2J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        lblC3J2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 101, 61)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblC4J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(lblC5J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblC1J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblC2J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblC3J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblC4J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblC5J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblC1J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblC2J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblC3J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblC1J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC2J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC3J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC4J2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC5J2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC3J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblC1J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblC2J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblC4J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblC5J1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout btnOtraLayout = new javax.swing.GroupLayout(btnOtra);
        btnOtra.setLayout(btnOtraLayout);
        btnOtraLayout.setHorizontalGroup(
            btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOtraLayout.createSequentialGroup()
                .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnOtraLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnOtraLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnOtraLayout.createSequentialGroup()
                                .addComponent(lblNumeroPartido)
                                .addGap(188, 188, 188)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(btnOtraLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOtraLayout.createSequentialGroup()
                        .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnOtraLayout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(btnNuevo)
                                .addGap(150, 150, 150))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOtraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnOtra1)
                                .addGap(18, 18, 18)
                                .addComponent(btnStop1)
                                .addGap(101, 101, 101)))
                        .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStart)
                            .addComponent(btnEvaluar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOtraLayout.createSequentialGroup()
                                .addComponent(btnSaldo)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOtraLayout.createSequentialGroup()
                                .addComponent(btnOtra2)
                                .addGap(18, 18, 18)
                                .addComponent(btnStop2)
                                .addGap(88, 88, 88)))))
                .addGap(51, 51, 51))
        );
        btnOtraLayout.setVerticalGroup(
            btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOtraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(jLabel2)
                    .addComponent(lblNumeroPartido))
                .addGap(18, 18, 18)
                .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOtraLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnStop1)
                                .addComponent(btnOtra1))
                            .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnStop2)
                                .addComponent(btnOtra2)))
                        .addGap(18, 18, 18))
                    .addGroup(btnOtraLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(btnOtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEvaluar)
                    .addComponent(btnSaldo))
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnOtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOtra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApuesta2ActionPerformed

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void btnOtra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtra2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtra2ActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtApuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApuesta1ActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void btnStop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStop2ActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnStop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStop1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        String cedula1=this.txtCedula1.getText();
         String cedula2=this.txtCedula2.getText();
         int apuesta1=Integer.parseInt(this.txtApuesta1.getText());
         int apuesta2=Integer.parseInt(this.txtApuesta2.getText());
         String fecha=this.lblFecha.getText();
         
        String [] cartas=this.myCasino.startBlackjackDos(apuesta1, apuesta2, cedula1, cedula2, fecha);
        JLabel cartasEtiqueda[] = {this.lblNumeroPartido,this.lblC1J1,this.lblC2J1,this.lblC1J2,this.lblC2J2 };
        this.etiquetas=cartasEtiqueda;
        for(int i=0;i<cartasEtiqueda.length;i++){
                cartasEtiqueda[i].setText(cartas[i]);
         }
           
    }//GEN-LAST:event_btnStartActionPerformed
   
    public void modificarLblJug2(){
        this.lblJ2.setText("CRUPIER");
        this.lblJ1.setText("JUGADOR"); 
    }
    
    private void btnOtra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtra1ActionPerformed

    private void txtNombre1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombre1MousePressed
        // TODO add your handling code here:
        this.txtNombre1.setText("");
    }//GEN-LAST:event_txtNombre1MousePressed

    private void txtCedula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula1ActionPerformed

    private void txtCedula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedula2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEvaluar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel btnOtra;
    private javax.swing.JButton btnOtra1;
    private javax.swing.JButton btnOtra2;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop1;
    private javax.swing.JButton btnStop2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblC1J1;
    private javax.swing.JLabel lblC1J2;
    private javax.swing.JLabel lblC2J1;
    private javax.swing.JLabel lblC2J2;
    private javax.swing.JLabel lblC3J1;
    private javax.swing.JLabel lblC3J2;
    private javax.swing.JLabel lblC4J1;
    private javax.swing.JLabel lblC4J2;
    private javax.swing.JLabel lblC5J1;
    private javax.swing.JLabel lblC5J2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblJ1;
    private javax.swing.JLabel lblJ2;
    private javax.swing.JLabel lblJapuesta1;
    private javax.swing.JLabel lblJapuesta2;
    private javax.swing.JLabel lblJapuesta3;
    private javax.swing.JLabel lblJnombre1;
    private javax.swing.JLabel lblJnombre2;
    private javax.swing.JLabel lblJnombre3;
    private javax.swing.JLabel lblNumeroPartido;
    private javax.swing.JTextField txtApuesta1;
    private javax.swing.JTextField txtApuesta2;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JTextField txtCedula2;
    private javax.swing.JTextArea txtJug1;
    private javax.swing.JTextArea txtJug2;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables
}
